version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 3000:3000
    env_file:
      - .env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - 4000:4000
    env_file:
      - .env

  mongo:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./db/mongo-volume:/data/db
    logging:
      driver: none

  redis:
    image: redis
    restart: always
    logging:
      driver: none
