version: '3.8'
services:
  client:
    profiles:
      - donotstart
  server:
    profiles:
      - donotstart

  mongo:
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./db/mongo-volume:/data/db
    ports:
      - '27017:27017'

  redis:
    ports:
      - '6379:6379'
