version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=http://51.38.112.108/api/v1
        - VITE_RUN_BY=docker
        - VITE_V=2
    ports:
      - '8080:80'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - NODE_V=2
