version: '3.8'
services:
  client:
    volumes:
      - ./client:/app

  server:
    volumes:
      - ./server:/app

  mongo:
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./db/mongo-volume:/data/db
