FROM node:alpine
WORKDIR /app
COPY client/package*.json ./
COPY . .
RUN yarn install
RUN yarn build

## this is stage two , where the app actually runs

FROM node:alpine

WORKDIR /app
COPY client/package*.json ./
RUN yarn install --production=true
COPY --from=0 /app/dist ./dist
EXPOSE 4000
ENV NODE_ENV production
CMD yarn start