name: deploy-server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Building the Image
        run: cd server && docker build -f Dockerfile.prod -t omarauf/late-server .

      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: docker push omarauf/late-server

      - name: Deploy the App to Dokku
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.DOMAIN }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'sudo docker pull omarauf/late-server && dokku ps:rebuild late-server'
