name: deploy-client

on:
  push:
    branches: 
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
      - uses: actions/checkout@v2
      - run: cd client && docker build -f Dockerfile.prod --build-arg VITE_V=10 -t omarauf/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push omarauf/client
