name: server-client

on:
  push:
    branches: 
      - main
    paths:
      - 'server/**'
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build image
        run: cd server && docker build -f Dockerfile.prod -t omarauf/server .

      - name: login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: push
        run: docker push omarauf/late-server
